---
- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart etcd
  become: true
  ansible.builtin.service:
    name: etcd
    state: restarted
    enabled: true
    daemon_reload: true

- name: Start Patroni
  become: true
  ansible.builtin.service:
    name: patroni
    state: restarted
    enabled: true
    daemon_reload: true
  listen: "restart patroni"

- name: Start vip-manager
  become: true
  ansible.builtin.service:
    name: vip-manager
    state: restarted
    enabled: true
    daemon_reload: true
  listen: "restart vip-manager"
